import Head from 'next/head'
import generateStaticMapURL from '../../utils/map-utils'

export default function Home() {
  const staticImageURL = generateStaticMapURL({
    center: "Eiffel+Tower,Paris",
    zoom: 12,
    size: "800x600",
    markers: "color:red|label:A|Eiffel+Tower,Paris",
  });

  return (
    <>
      <Head>
        <title>Practical Google Maps API for Front-end Developers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Eiffel Tower, Paris</h1>
        <img alt="Map of Eiffel Tower, Paris" src={staticImageURL} />
      </main>
    </>
  )
}
